name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --split-per-abi
      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: apk-build
          path: build/app/outputs/apk/release
  build_ios:
   runs-on: macos-latest
   steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter clean
    - run: >
            flutter build ios
            --release --no-codesign
    - name: Upload iPA
      uses: actions/upload-artifact@main
      with:
        name: ios-build
        path: build/ios/iphoneos
